import type { CategoryId, DestinationSlug } from "@/lib/constants";

export type BadgeDifficulty = "easy" | "medium" | "hard" | "legendary";
export type BadgeRarity = "common" | "rare" | "epic" | "legendary";

export interface SampleBadge {
  id: string;
  name: string;
  description: string;
  points: number;
  difficulty: BadgeDifficulty;
  rarity: BadgeRarity;
  category: CategoryId;
  imageUrl: string;
}

export interface SampleGuide {
  id: string;
  name: string;
  businessName: string;
  rating: number;
  reviewCount: number;
  specialties: string[];
  initials: string;
}

export type CategoryBreakdown = Record<CategoryId, number>;

const CR_BADGES: SampleBadge[] = [
  {
    id: "cr-arenal",
    name: "Arenal Volcano Hike",
    description: "Trek the lava-carved trails of an active volcano",
    points: 400,
    difficulty: "hard",
    rarity: "epic",
    category: "nature",
    imageUrl: "/assets/badge-images/arenal-gazer.jpg",
  },
  {
    id: "cr-sloth",
    name: "Sloth Spotter",
    description: "Find a wild sloth in the rainforest canopy",
    points: 150,
    difficulty: "easy",
    rarity: "common",
    category: "wildlife",
    imageUrl: "/assets/badge-images/sloth-spotter.jpg",
  },
  {
    id: "cr-manuel-antonio",
    name: "Manuel Antonio Wildlife",
    description: "Spot capuchins, iguanas, and macaws in one day",
    points: 250,
    difficulty: "medium",
    rarity: "rare",
    category: "wildlife",
    imageUrl: "/assets/badge-images/manuel-antonio.jpg",
  },
  {
    id: "cr-ceviche",
    name: "Tico Ceviche Tasting",
    description: "Try the classic lime-cured fish at a local soda",
    points: 100,
    difficulty: "easy",
    rarity: "common",
    category: "food",
    imageUrl: "/assets/badge-images/ceviche-tico.jpg",
  },
  {
    id: "cr-monteverde",
    name: "Monteverde Cloud Forest",
    description: "Walk the misty hanging bridges above the canopy",
    points: 300,
    difficulty: "medium",
    rarity: "rare",
    category: "nature",
    imageUrl: "/assets/badge-images/monteverde-mist.jpg",
  },
  {
    id: "cr-pacuare",
    name: "Pacuare River Rafting",
    description: "Run Class IV rapids through pristine jungle",
    points: 450,
    difficulty: "hard",
    rarity: "epic",
    category: "adventure",
    imageUrl: "/assets/badge-images/white-water-pacuare.jpg",
  },
  {
    id: "cr-pacific-sunset",
    name: "Pacific Sunset",
    description: "Watch the sun melt into the Nicoya Peninsula",
    points: 100,
    difficulty: "easy",
    rarity: "common",
    category: "beaches",
    imageUrl: "/assets/badge-images/pacific-sunset.jpg",
  },
  {
    id: "cr-pura-vida-legend",
    name: "Pura Vida Legend",
    description: "Complete every category — claim the legend status",
    points: 1000,
    difficulty: "legendary",
    rarity: "legendary",
    category: "premium",
    imageUrl: "/assets/badge-images/pura-vida-legend.jpg",
  },
];

const IS_BADGES: SampleBadge[] = [
  {
    id: "is-blue-lagoon",
    name: "Blue Lagoon Soak",
    description: "Float in geothermal milky-blue water",
    points: 150,
    difficulty: "easy",
    rarity: "common",
    category: "beaches",
    imageUrl: "/assets/badge-images/is-blue-lagoon.jpg",
  },
  {
    id: "is-gullfoss",
    name: "Gullfoss Waterfall",
    description: "Stand in the spray of the Golden Falls",
    points: 200,
    difficulty: "easy",
    rarity: "common",
    category: "nature",
    imageUrl: "/assets/badge-images/is-gullfoss-waterfall.jpg",
  },
  {
    id: "is-glacier",
    name: "Sólheimajökull Glacier Hike",
    description: "Strap on crampons and walk an ancient ice tongue",
    points: 450,
    difficulty: "hard",
    rarity: "epic",
    category: "adventure",
    imageUrl: "/assets/badge-images/is-glacier-hike-solheimajokull.jpg",
  },
  {
    id: "is-puffin",
    name: "Puffin Watch",
    description: "Spot Atlantic puffins on the Dyrhólaey cliffs",
    points: 250,
    difficulty: "medium",
    rarity: "rare",
    category: "wildlife",
    imageUrl: "/assets/badge-images/is-puffin-dyrholaey.jpg",
  },
  {
    id: "is-fimmvorduhals",
    name: "Fimmvörðuháls Trek",
    description: "25 km traverse between two glaciers",
    points: 800,
    difficulty: "legendary",
    rarity: "legendary",
    category: "explorer",
    imageUrl: "/assets/badge-images/is-fimmvorduhals-trek.jpg",
  },
  {
    id: "is-reynisfjara",
    name: "Reynisfjara Black Sand",
    description: "Visit the basalt sea stacks at Iceland's most iconic beach",
    points: 250,
    difficulty: "medium",
    rarity: "rare",
    category: "beaches",
    imageUrl: "/assets/badge-images/is-reynisfjara.jpg",
  },
  {
    id: "is-skogafoss",
    name: "Skógafoss Falls",
    description: "Climb the staircase beside a 60m thundering wall",
    points: 200,
    difficulty: "easy",
    rarity: "common",
    category: "nature",
    imageUrl: "/assets/badge-images/is-skogafoss.jpg",
  },
  {
    id: "is-ice-cave",
    name: "Vatnajökull Ice Cave",
    description: "Descend into a sapphire-blue cave under the glacier",
    points: 500,
    difficulty: "hard",
    rarity: "epic",
    category: "premium",
    imageUrl: "/assets/badge-images/is-ice-cave-vatnajokull.jpg",
  },
];

const PE_BADGES: SampleBadge[] = [
  {
    id: "pe-machu-picchu",
    name: "Machu Picchu Sunrise",
    description: "Watch dawn break over the Lost City of the Incas",
    points: 500,
    difficulty: "hard",
    rarity: "epic",
    category: "culture",
    imageUrl: "/assets/heroes/hero-peru.jpg",
  },
  {
    id: "pe-inca-trail",
    name: "Inca Trail Trek",
    description: "Four-day pilgrimage on stone paved by ancient builders",
    points: 1000,
    difficulty: "legendary",
    rarity: "legendary",
    category: "explorer",
    imageUrl: "/assets/heroes/hero-peru.jpg",
  },
  {
    id: "pe-rainbow-mountain",
    name: "Rainbow Mountain",
    description: "Hike Vinicunca's striped mineral ridges at 5200m",
    points: 450,
    difficulty: "hard",
    rarity: "epic",
    category: "nature",
    imageUrl: "/assets/heroes/hero-peru.jpg",
  },
  {
    id: "pe-sacred-valley",
    name: "Sacred Valley Tour",
    description: "Walk the terraces of Pisac and Ollantaytambo",
    points: 300,
    difficulty: "medium",
    rarity: "rare",
    category: "culture",
    imageUrl: "/assets/heroes/hero-peru.jpg",
  },
  {
    id: "pe-ceviche",
    name: "Ceviche Limeño",
    description: "Try Peru's national dish at a Lima cevichería",
    points: 100,
    difficulty: "easy",
    rarity: "common",
    category: "food",
    imageUrl: "/assets/heroes/hero-peru.jpg",
  },
  {
    id: "pe-titicaca",
    name: "Lake Titicaca Floating Islands",
    description: "Visit the reed islands of the Uros people",
    points: 250,
    difficulty: "medium",
    rarity: "rare",
    category: "culture",
    imageUrl: "/assets/heroes/hero-peru.jpg",
  },
  {
    id: "pe-condor",
    name: "Andean Condor Spotting",
    description: "Watch condors soar at Colca Canyon at dawn",
    points: 400,
    difficulty: "hard",
    rarity: "epic",
    category: "wildlife",
    imageUrl: "/assets/heroes/hero-peru.jpg",
  },
  {
    id: "pe-cusco",
    name: "Cusco Plaza de Armas",
    description: "Stand in the heart of the former Inca capital",
    points: 100,
    difficulty: "easy",
    rarity: "common",
    category: "culture",
    imageUrl: "/assets/heroes/hero-peru.jpg",
  },
];

const TH_BADGES: SampleBadge[] = [
  {
    id: "th-phi-phi",
    name: "Phi Phi Islands",
    description: "Snorkel turquoise water around limestone karsts",
    points: 200,
    difficulty: "easy",
    rarity: "common",
    category: "beaches",
    imageUrl: "/assets/heroes/hero-thailand.jpg",
  },
  {
    id: "th-temples",
    name: "Chiang Mai Temple Tour",
    description: "Visit Wat Phra Singh, Chedi Luang, and Doi Suthep",
    points: 300,
    difficulty: "medium",
    rarity: "rare",
    category: "culture",
    imageUrl: "/assets/heroes/hero-thailand.jpg",
  },
  {
    id: "th-pad-thai",
    name: "Pad Thai Master",
    description: "Take a Bangkok cooking class and plate one yourself",
    points: 150,
    difficulty: "easy",
    rarity: "common",
    category: "food",
    imageUrl: "/assets/heroes/hero-thailand.jpg",
  },
  {
    id: "th-elephant",
    name: "Ethical Elephant Sanctuary",
    description: "Bathe and feed rescued elephants in the north",
    points: 350,
    difficulty: "medium",
    rarity: "rare",
    category: "wildlife",
    imageUrl: "/assets/heroes/hero-thailand.jpg",
  },
  {
    id: "th-railay",
    name: "Railay Rock Climbing",
    description: "Sport climb above white-sand beaches",
    points: 450,
    difficulty: "hard",
    rarity: "epic",
    category: "adventure",
    imageUrl: "/assets/heroes/hero-thailand.jpg",
  },
  {
    id: "th-doi-inthanon",
    name: "Doi Inthanon Summit",
    description: "Reach the highest point in Thailand",
    points: 400,
    difficulty: "hard",
    rarity: "epic",
    category: "nature",
    imageUrl: "/assets/heroes/hero-thailand.jpg",
  },
  {
    id: "th-songkran",
    name: "Songkran Festival",
    description: "Join Thailand's nationwide water-fight new year",
    points: 800,
    difficulty: "legendary",
    rarity: "legendary",
    category: "culture",
    imageUrl: "/assets/heroes/hero-thailand.jpg",
  },
  {
    id: "th-tom-yum",
    name: "Tom Yum Goong",
    description: "Slurp the iconic spicy-sour shrimp soup",
    points: 200,
    difficulty: "medium",
    rarity: "rare",
    category: "food",
    imageUrl: "/assets/heroes/hero-thailand.jpg",
  },
];

const SA_BADGES: SampleBadge[] = [
  {
    id: "sa-alula",
    name: "AlUla Sandstone",
    description: "Wander red-rock formations carved by 100M years",
    points: 300,
    difficulty: "medium",
    rarity: "rare",
    category: "nature",
    imageUrl: "/assets/heroes/hero-saudi-arabia.jpg",
  },
  {
    id: "sa-edge-of-the-world",
    name: "Edge of the World",
    description: "Stand on a 300m cliff over the empty plain",
    points: 450,
    difficulty: "hard",
    rarity: "epic",
    category: "adventure",
    imageUrl: "/assets/heroes/hero-saudi-arabia.jpg",
  },
  {
    id: "sa-madain-saleh",
    name: "Hegra Tombs",
    description: "Explore Nabataean tombs at Saudi's first UNESCO site",
    points: 500,
    difficulty: "hard",
    rarity: "epic",
    category: "culture",
    imageUrl: "/assets/heroes/hero-saudi-arabia.jpg",
  },
  {
    id: "sa-diriyah",
    name: "Diriyah Heritage",
    description: "Walk the mud-brick birthplace of the Saudi state",
    points: 200,
    difficulty: "easy",
    rarity: "common",
    category: "culture",
    imageUrl: "/assets/heroes/hero-saudi-arabia.jpg",
  },
  {
    id: "sa-red-sea",
    name: "Red Sea Diving",
    description: "Dive untouched coral reefs off the Hejaz coast",
    points: 400,
    difficulty: "hard",
    rarity: "epic",
    category: "adventure",
    imageUrl: "/assets/heroes/hero-saudi-arabia.jpg",
  },
  {
    id: "sa-rub-al-khali",
    name: "Empty Quarter Desert",
    description: "Cross the world's largest sand sea by 4x4",
    points: 800,
    difficulty: "legendary",
    rarity: "legendary",
    category: "explorer",
    imageUrl: "/assets/heroes/hero-saudi-arabia.jpg",
  },
  {
    id: "sa-coffee",
    name: "Saudi Coffee Ceremony",
    description: "Share gahwa and dates with locals",
    points: 100,
    difficulty: "easy",
    rarity: "common",
    category: "food",
    imageUrl: "/assets/heroes/hero-saudi-arabia.jpg",
  },
  {
    id: "sa-elephant-rock",
    name: "Elephant Rock at Sunset",
    description: "Photograph AlUla's iconic stone elephant in golden hour",
    points: 250,
    difficulty: "medium",
    rarity: "rare",
    category: "premium",
    imageUrl: "/assets/heroes/hero-saudi-arabia.jpg",
  },
];

const AK_BADGES: SampleBadge[] = [
  {
    id: "ak-denali",
    name: "Denali Sighting",
    description: "Catch the cloud-shrouded peak on a clear day",
    points: 500,
    difficulty: "hard",
    rarity: "epic",
    category: "nature",
    imageUrl: "/assets/heroes/hero-alaska.jpg",
  },
  {
    id: "ak-glacier-bay",
    name: "Glacier Bay Cruise",
    description: "Watch a tidewater glacier calve into the fjord",
    points: 300,
    difficulty: "medium",
    rarity: "rare",
    category: "nature",
    imageUrl: "/assets/heroes/hero-alaska.jpg",
  },
  {
    id: "ak-whales",
    name: "Humpback Whale Watching",
    description: "See bubble-net feeding in southeast Alaska",
    points: 250,
    difficulty: "easy",
    rarity: "common",
    category: "wildlife",
    imageUrl: "/assets/heroes/hero-alaska.jpg",
  },
  {
    id: "ak-aurora",
    name: "Northern Lights Aurora",
    description: "Chase the aurora borealis under Fairbanks skies",
    points: 500,
    difficulty: "hard",
    rarity: "epic",
    category: "nature",
    imageUrl: "/assets/heroes/hero-alaska.jpg",
  },
  {
    id: "ak-salmon",
    name: "Wild Salmon Run",
    description: "Catch (and release) a king salmon on the Kenai",
    points: 250,
    difficulty: "medium",
    rarity: "rare",
    category: "food",
    imageUrl: "/assets/heroes/hero-alaska.jpg",
  },
  {
    id: "ak-kayak",
    name: "Kenai Fjords Kayak",
    description: "Paddle past harbor seals and sea otters",
    points: 400,
    difficulty: "hard",
    rarity: "epic",
    category: "adventure",
    imageUrl: "/assets/heroes/hero-alaska.jpg",
  },
  {
    id: "ak-bear",
    name: "Brown Bear Spotting",
    description: "Observe brown bears at Brooks Falls salmon run",
    points: 450,
    difficulty: "hard",
    rarity: "epic",
    category: "wildlife",
    imageUrl: "/assets/heroes/hero-alaska.jpg",
  },
  {
    id: "ak-iditarod",
    name: "Iditarod Trail",
    description: "Witness the Last Great Race start in Anchorage",
    points: 800,
    difficulty: "legendary",
    rarity: "legendary",
    category: "culture",
    imageUrl: "/assets/heroes/hero-alaska.jpg",
  },
];

export const SAMPLE_BADGES: Record<DestinationSlug, SampleBadge[]> = {
  "costa-rica": CR_BADGES,
  iceland: IS_BADGES,
  peru: PE_BADGES,
  thailand: TH_BADGES,
  "saudi-arabia": SA_BADGES,
  alaska: AK_BADGES,
};

export const SAMPLE_GUIDES: Record<DestinationSlug, SampleGuide[]> = {
  "costa-rica": [
    {
      id: "cr-g1",
      name: "Carlos Méndez",
      businessName: "Pura Vida Tours",
      rating: 4.9,
      reviewCount: 128,
      specialties: ["Wildlife", "Adventure"],
      initials: "CM",
    },
    {
      id: "cr-g2",
      name: "Ana Rojas",
      businessName: "Cloud Forest Adventures",
      rating: 4.8,
      reviewCount: 94,
      specialties: ["Nature", "Photography"],
      initials: "AR",
    },
    {
      id: "cr-g3",
      name: "Rodrigo Solís",
      businessName: "Surf Coast CR",
      rating: 5.0,
      reviewCount: 67,
      specialties: ["Beaches", "Surfing"],
      initials: "RS",
    },
  ],
  iceland: [
    {
      id: "is-g1",
      name: "Björn Sigurðsson",
      businessName: "Reykjavík Excursions",
      rating: 4.9,
      reviewCount: 211,
      specialties: ["Glaciers", "Photography"],
      initials: "BS",
    },
    {
      id: "is-g2",
      name: "Helga Jónsdóttir",
      businessName: "Aurora Hunters",
      rating: 5.0,
      reviewCount: 156,
      specialties: ["Northern Lights", "Nature"],
      initials: "HJ",
    },
    {
      id: "is-g3",
      name: "Eiríkur Ólafsson",
      businessName: "Highland Treks",
      rating: 4.7,
      reviewCount: 88,
      specialties: ["Hiking", "Adventure"],
      initials: "EÓ",
    },
  ],
  peru: [
    {
      id: "pe-g1",
      name: "María Quispe",
      businessName: "Inca Trails Co",
      rating: 4.9,
      reviewCount: 173,
      specialties: ["Inca Trail", "Culture"],
      initials: "MQ",
    },
    {
      id: "pe-g2",
      name: "Pedro Mamani",
      businessName: "Sacred Valley Guides",
      rating: 4.8,
      reviewCount: 102,
      specialties: ["Culture", "Photography"],
      initials: "PM",
    },
    {
      id: "pe-g3",
      name: "Luis Huamán",
      businessName: "Andean Adventures",
      rating: 4.7,
      reviewCount: 76,
      specialties: ["Adventure", "Wildlife"],
      initials: "LH",
    },
  ],
  thailand: [
    {
      id: "th-g1",
      name: "Somchai Lao",
      businessName: "Bangkok Bites",
      rating: 4.9,
      reviewCount: 142,
      specialties: ["Food", "Culture"],
      initials: "SL",
    },
    {
      id: "th-g2",
      name: "Niran Wong",
      businessName: "Krabi Climbs",
      rating: 4.8,
      reviewCount: 96,
      specialties: ["Adventure", "Beaches"],
      initials: "NW",
    },
    {
      id: "th-g3",
      name: "Pranee Tan",
      businessName: "Northern Thailand Tours",
      rating: 5.0,
      reviewCount: 118,
      specialties: ["Culture", "Wellness"],
      initials: "PT",
    },
  ],
  "saudi-arabia": [
    {
      id: "sa-g1",
      name: "Khalid Al-Mansour",
      businessName: "Desert Voyages",
      rating: 4.8,
      reviewCount: 87,
      specialties: ["Desert", "Adventure"],
      initials: "KM",
    },
    {
      id: "sa-g2",
      name: "Layla Al-Saud",
      businessName: "Heritage Walks",
      rating: 4.9,
      reviewCount: 104,
      specialties: ["Culture", "Photography"],
      initials: "LS",
    },
    {
      id: "sa-g3",
      name: "Omar Al-Otaibi",
      businessName: "Red Sea Divers",
      rating: 4.7,
      reviewCount: 62,
      specialties: ["Diving", "Beaches"],
      initials: "OO",
    },
  ],
  alaska: [
    {
      id: "ak-g1",
      name: "Sarah Inukpuk",
      businessName: "Last Frontier Guides",
      rating: 4.9,
      reviewCount: 134,
      specialties: ["Wildlife", "Glaciers"],
      initials: "SI",
    },
    {
      id: "ak-g2",
      name: "Tom Henderson",
      businessName: "Denali Treks",
      rating: 5.0,
      reviewCount: 91,
      specialties: ["Mountaineering", "Adventure"],
      initials: "TH",
    },
    {
      id: "ak-g3",
      name: "Lisa Aleksuk",
      businessName: "Aurora Borealis Co",
      rating: 4.8,
      reviewCount: 78,
      specialties: ["Northern Lights", "Photography"],
      initials: "LA",
    },
  ],
};

export const CATEGORY_BREAKDOWN: Record<DestinationSlug, CategoryBreakdown> = {
  "costa-rica": {
    nature: 18,
    wildlife: 16,
    beaches: 14,
    adventure: 15,
    food: 14,
    culture: 12,
    explorer: 8,
    premium: 6,
  },
  iceland: {
    nature: 22,
    wildlife: 12,
    beaches: 6,
    adventure: 16,
    food: 8,
    culture: 12,
    explorer: 18,
    premium: 6,
  },
  peru: {
    nature: 14,
    wildlife: 10,
    beaches: 4,
    adventure: 14,
    food: 10,
    culture: 18,
    explorer: 6,
    premium: 4,
  },
  thailand: {
    nature: 14,
    wildlife: 10,
    beaches: 18,
    adventure: 14,
    food: 18,
    culture: 12,
    explorer: 8,
    premium: 6,
  },
  "saudi-arabia": {
    nature: 16,
    wildlife: 8,
    beaches: 8,
    adventure: 12,
    food: 8,
    culture: 14,
    explorer: 5,
    premium: 4,
  },
  alaska: {
    nature: 18,
    wildlife: 18,
    beaches: 6,
    adventure: 18,
    food: 10,
    culture: 8,
    explorer: 8,
    premium: 6,
  },
};
